Wor-49-interest
WorkshopMDS/vivatech-back pull request #10
Opened 2023-05-08 14:00 UTC by Maengdok

# Interest
As far as we know interests are defined as follow:
- Label : Which represents the title of the interest

## Features

### GET /interests
- Get list of interests

### GET /interest/:id
- Get an interest from its ID

### POST /interest
- Allow to create a new interest and push it into the database

### PATCH /interest/:id
- Allow to update an existing interest

### DELETE /interest/:id
- Allow to remove an existing interest from the database

### Tests

- Test response status code on valid requests
- Test returned values
- Test response status codes on invalid requests

2023-05-09 06:34 UTC, remirubis requested changes
Bien ouej ! Quelques questions, j'ai pas de wifi les 2-3 prochains jours donc c'est pas ultra grave ça peut passer sans modifs pour les autres reviewers ;)

2023-05-09 06:34 UTC, remirubis commented on src/__tests__/mockups/exhibitor.mock.ts
> +    interests: {},
Etrange, ça devrait être un array vide non ?

2023-05-09 06:34 UTC, remirubis commented on src/models/exhibitor.model.ts
> +  },
Ça devrait être un array d'id ici donc ça :
```suggestion
  interests: [{
    type: Schema.Types.ObjectId,
    ref: 'Interests',
  }],
```

2023-05-13 04:34 UTC, remirubis approved these changes
LGTM!  Bien ouej :)

2023-05-23 07:47 UTC, kilianpichard approved these changes
LGTM !

2023-05-23 07:48 UTC, merged