Wor 17 recuperation des exposants cote api
WorkshopMDS/vivatech-back pull request #4
Opened 2023-05-02 14:47 UTC by Maengdok

# Exhibitor
An exhibitor represent a society that will have a stand during VivaTech event.

As far as we know exhibitor are defined as follow:
- Name : Which represents the name of the exhibitor
- Picture : Which represents the URL of the exhibitor's picture
- Place : Which represents the stand their are assigned to
- Sectors: Which represents the sectors their are present and that are used to aim users
- Interests: Which represents the interests used to aim users

## Features

### GET /exhibitors
- Get list of exhibitors

### GET /exhibitor/:id
- Get an exhibitor from its ID

### POST /exhibitor/add
- Allow to create a new exhibitor and push it into the database

### PATCH /exhibitor/update/:id
- Allow to update an existing exhibitor

### DELETE /exhibitor/delete/:id
- Allow to remove an existing exhibitor from the database

### Tests

- Test response status code on valid requests
- Test returned values
- Test response status codes on invalid requests

2023-05-02 22:49 UTC, remirubis requested changes
Bien joué ! J'ai quelques questions + suggestions + changements à proposer, on en parle ensemble si tu veux :)

2023-05-02 22:49 UTC, remirubis commented on src/controllers/exhibitor.controller.ts
> +        description: HttpStatusCodesDescriptions.SUCCESS,
On voudrait pas pouvoir générer la description automatiquement en fonction du status code ?

2023-05-02 22:49 UTC, remirubis commented on src/controllers/exhibitor.controller.ts
> +        name: 'Success',
Dans le cas des erreurs tu devrais peut-être automatiquement généré un name 'Error' et si on veut l'override on peut, ça fait bcp de code dupliqué

2023-05-02 22:49 UTC, remirubis commented on src/controllers/exhibitor.controller.ts
> +    res.status(HttpStatusCodes.SUCCESS).json(apiResponse);
On a une duplication du `HttpStatusCodes` entre la class ApiResponse et ici c'est pas top

2023-05-02 22:49 UTC, remirubis commented on src/controllers/exhibitor.controller.ts
> +  }
Il faudrait ajouter une props debug à la classe qui est return uniquement si le `process.env.NODE_ENV !== 'production'` pour éviter de perdre le context de l'erreur en dev ce qui pourrait être très chiant à debug

2023-05-02 22:49 UTC, remirubis commented on src/controllers/exhibitor.controller.ts
> +      req.body,
Pas très secure de passer le body entier, risque de modification d'autre entrée dans le modèle

2023-05-02 22:49 UTC, remirubis commented on src/controllers/exhibitor.controller.ts
> +      {"_id": req.params.id},
Tips : tu peux juste mettre `id` à la place de `_id` mongoose le comprendra

2023-05-02 22:49 UTC, remirubis commented on src/controllers/exhibitor.controller.ts
> +      {"_id": req.params.id},
Tips 2 : Tu peux réduire la requête en utilisant `findByIdAndUpdate`

2023-05-02 22:49 UTC, remirubis commented on src/controllers/exhibitor.controller.ts
> +    const exhibitor: IExhibitor | null = await Exhibitor.findOneAndRemove({"_id": req.params.id});
Same que pour l'update tu peux utiliser `findByIdAndDelete`

2023-05-02 22:49 UTC, remirubis commented on src/server.ts
> +    .connect(URI, { })
Une raison particulière pour ça ?

2023-05-02 22:49 UTC, remirubis commented on src/router.ts
> +router.use((_req: Request, _res: Response, next: NextFunction) => {
Pour rendre le router le plus simple possible j'aurais bien sortit ça du `router.ts` pour le mettre dans un `default.routers.ts`

2023-05-02 22:49 UTC, remirubis commented on src/models/exhibitor.model.ts
> +    }
Pour info, pour gagner en place + lisibilité tu peux faire :
```suggestion
    picture: String,
    place: String,
    sectors: String[],
    interests: String[]
```

2023-05-03 09:06 UTC, Maengdok commented on src/server.ts
> +    .connect(URI, { })
Il l'a juste repris d'un de tes commits parce que j'y ai pas touché

2023-05-03 13:19 UTC, closed without merging